sudo: required
services:
  - docker

before_install:
  - docker build -t jgschneider/docker-frontend -f Dockerfile.dev .

script:
  - docker run jgschneider/docker-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-Frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-155763739380"
  bucket_path: "Docker-Frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
