sudo: required
services:
  - docker

before_install:
  - docker build -t jgschneider/docker-frontend -f Dockerfile.dev .

script:
  - docker run jgschneider/docker-frontend npm run test -- --coverage
